remove some redundant logic from import-*-pkg scripts
repo-remove handles both .db and .files at once, there's no need to use it
again. A second time produces the following error, it was hiding behind the
pipe to sed:

ERROR: '${_repo}.files.tar.gz' doesn't have a valid database archive extension.